In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = r"C:\Users\KIIT\OneDrive\Desktop\WA_Fn-UseC_-Telco-Customer-Churn.xlsx"
df = pd.read_excel(file_path)

# Quick look
print(df.shape)
df.head()

(7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
print(df.isnull().sum())

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [5]:

#get summary of dataset 
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None

In [7]:
df_clean = df.copy()
df_clean.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [8]:
# Convert TotalCharges to numeric
df_clean["TotalCharges"] = pd.to_numeric(df_clean["TotalCharges"], errors="coerce")

In [9]:
df_clean.isna().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [11]:
#FILLING MISSING VALUES WITH MEDIAN VALUE

df_clean["TotalCharges"] = df_clean["TotalCharges"].fillna(df_clean["TotalCharges"].median())

In [12]:
df_clean.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [13]:
yes_no_cols = ["Partner", "Dependents", "PhoneService", "PaperlessBilling", "Churn"]

for col in yes_no_cols:
    df_clean[col + "_Flag"] = df_clean[col].map({"Yes": 1, "No": 0})

In [14]:
df_clean["SeniorCitizen"] = df_clean["SeniorCitizen"].map({0: "No", 1: "Yes"})

In [16]:
pd.set_option('display.max_columns', None)  pd.set_option('display.width', None)        pd.set_option('display.max_colwidth', None) 
df_clean.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Partner_Flag,Dependents_Flag,PhoneService_Flag,PaperlessBilling_Flag,Churn_Flag
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,0,0,1,0
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,0,0,1,0,0
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0,0,1,1,1
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0,0,0,0,0
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0,1,1,1

In [17]:
internet_cols = ["OnlineSecurity", "OnlineBackup", "DeviceProtection", 
                 "TechSupport", "StreamingTV", "StreamingMovies"]

for col in internet_cols:
    df_clean[col] = df_clean[col].replace("No internet service", "No")

In [18]:
for col in internet_cols:
    df_clean[col + "_Flag"] = df_clean[col].map({"Yes": 1, "No": 0})

In [19]:

df_clean.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Partner_Flag,Dependents_Flag,PhoneService_Flag,PaperlessBilling_Flag,Churn_Flag,OnlineSecurity_Flag,OnlineBackup_Flag,DeviceProtection_Flag,TechSupport_Flag,StreamingTV_Flag,StreamingMovies_Flag
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,0,0,1,0,0,1,0,0,0,0
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,0,0,1,0,0,1,0,1,0,0,0
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0,0,1,1,1,1,1,0,0,0,0
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0,0,0,0,0,1,0,1,1,0,0
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0,1,1,1,0,0,0,0,0,0

In [20]:
cat_cols = ["gender", "Contract", "PaymentMethod", "InternetService", "MultipleLines"]
for col in cat_cols:
    df_clean[col] = df_clean[col].astype('category')

In [21]:
df_clean.dtypes

customerID                 object
gender                   category
SeniorCitizen              object
Partner                    object
Dependents                 object
tenure                      int64
PhoneService               object
MultipleLines            category
InternetService          category
OnlineSecurity             object
OnlineBackup               object
DeviceProtection           object
TechSupport                object
StreamingTV                object
StreamingMovies            object
Contract                 category
PaperlessBilling           object
PaymentMethod            category
MonthlyCharges            float64
TotalCharges              float64
Churn                      object
Partner_Flag                int64
Dependents_Flag             int64
PhoneService_Flag           int64
PaperlessBilling_Flag       int64
Churn_Flag                  int64
OnlineSecurity_Flag         int64
OnlineBackup_Flag           int64
DeviceProtection_Flag       int64
TechSupport_Flag            int64
StreamingTV_Flag            int64
StreamingMovies_Flag        int64
dtype: object

In [22]:
bins = [0, 12, 24, 48, 60, 72]
labels = ['0-12','13-24','25-48','49-60','61-72']

df_clean['tenure_group'] = pd.cut(df_clean['tenure'], bins=bins, labels=labels, right=True)

In [23]:
df_clean.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Partner_Flag,Dependents_Flag,PhoneService_Flag,PaperlessBilling_Flag,Churn_Flag,OnlineSecurity_Flag,OnlineBackup_Flag,DeviceProtection_Flag,TechSupport_Flag,StreamingTV_Flag,StreamingMovies_Flag,tenure_group
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,0,0,1,0,0,1,0,0,0,0,0-12
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,0,0,1,0,0,1,0,1,0,0,0,25-48
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0,0,1,1,1,1,1,0,0,0,0,0-12
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0,0,0,0,0,1,0,1,1,0,0,25-48
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0,1,1,1,0,0,0,0,0,0,0-12

In [24]:
df_clean['MultipleLines'] = df_clean['MultipleLines'].replace("No phone service", "No")

# Now create flag
df_clean['MultipleLines_Flag'] = df_clean['MultipleLines'].map({"Yes": 1, "No": 0})

C:\Users\KIIT\AppData\Local\Temp\ipykernel_16520\395406270.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_clean['MultipleLines'] = df_clean['MultipleLines'].replace("No phone service", "No")

In [28]:
df_clean['MultipleLines'].unique()

['No', 'Yes']
Categories (2, object): ['No', 'Yes']

In [29]:
df_clean_ndrop = df_clean.copy()
df_clean_ndrop.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Partner_Flag,Dependents_Flag,PhoneService_Flag,PaperlessBilling_Flag,Churn_Flag,OnlineSecurity_Flag,OnlineBackup_Flag,DeviceProtection_Flag,TechSupport_Flag,StreamingTV_Flag,StreamingMovies_Flag,tenure_group,MultipleLines_Flag
0,7590-VHVEG,Female,No,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,0,0,1,0,0,1,0,0,0,0,0-12,0
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,0,0,1,0,0,1,0,1,0,0,0,25-48,0
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0,0,1,1,1,1,1,0,0,0,0,0-12,0
3,7795-CFOCW,Male,No,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0,0,0,0,0,1,0,1,1,0,0,25-48,0
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0,1,1,1,0,0,0,0,0,0,0-12,0

In [31]:
# Export to CSV
df_clean.to_csv("Cleaned_dataset_Churn_Analysis.csv", index=False)

In [36]:
import pandas as pd
import mysql.connector  # or pyodbc for SQL Server

# 1. Connecting database
conn = mysql.connector.connect(
    host='127.0.0.1',
    user='root',
    password='Ankita221*',
    database='telecom_db'
)

# 2. Listing queries
queries = {
    'Overall_Churn': """
        SELECT COUNT(*) AS total_customers,
               SUM(Churn_Flag) AS churned_customers,
               ROUND(AVG(Churn_Flag)*100,2) AS churn_rate_percentage,
               COUNT(*) - SUM(Churn_Flag) AS retained_customers
        FROM telecom_customers;
    """,
    
    'Gender_Distribution': """
        SELECT gender, COUNT(*) AS count, ROUND(AVG(Churn_Flag)*100,2) AS churn_rate_percentage
        FROM telecom_customers
        GROUP BY gender;
    """,
    
    'SeniorCitizen_Distribution': """
        SELECT SeniorCitizen, COUNT(*) AS count, ROUND(AVG(Churn_Flag)*100,2) AS churn_rate_percentage
        FROM telecom_customers
        GROUP BY SeniorCitizen;
    """,
    
    'Partner_Distribution': """
        SELECT Partner, COUNT(*) AS count, ROUND(AVG(Churn_Flag)*100,2) AS churn_rate_percentage
        FROM telecom_customers
        GROUP BY Partner;
    """,
    
    'Dependents_Distribution': """
        SELECT Dependents, COUNT(*) AS count, ROUND(AVG(Churn_Flag)*100,2) AS churn_rate_percentage
        FROM telecom_customers
        GROUP BY Dependents;
    """,
    
    'Segment_Churn_Advanced': """
        WITH segment_churn AS (
            SELECT gender, SeniorCitizen, Partner, Dependents,
                   COUNT(*) AS total_customers,
                   SUM(Churn_Flag) AS churned_customers,
                   ROUND(AVG(Churn_Flag)*100,2) AS churn_rate_percentage
            FROM telecom_customers
            GROUP BY gender, SeniorCitizen, Partner, Dependents
        )
        SELECT *
        FROM segment_churn
        ORDER BY churn_rate_percentage DESC
        LIMIT 10;
    """,
    
    'Tenure_Group_Distribution': """
        SELECT tenure_group, COUNT(*) AS count, ROUND(AVG(Churn_Flag)*100,2) AS churn_rate_percentage
        FROM telecom_customers
        GROUP BY tenure_group
        ORDER BY count DESC;
    """,
    
    'Tenure_Trend': """
        SELECT tenure, COUNT(*) AS customer_count,
               ROUND(SUM(TotalCharges),2) AS total_revenue,
               ROUND(AVG(MonthlyCharges),2) AS avg_monthly_charge,
               ROUND(AVG(Churn_Flag)*100,2) AS churn_rate_percentage
        FROM telecom_customers
        GROUP BY tenure
        ORDER BY tenure;
    """,
    
    'Contract_Analysis': """
        SELECT Contract, COUNT(*) AS customer_count,
               ROUND(SUM(TotalCharges),2) AS total_revenue,
               ROUND(AVG(MonthlyCharges),2) AS avg_monthly_charge,
               ROUND(AVG(Churn_Flag)*100,2) AS churn_rate_percentage
        FROM telecom_customers
        GROUP BY Contract
        ORDER BY total_revenue DESC;
    """,
    
    'Service_Adoption_Counts': """
        SELECT 
            SUM(PhoneService_Flag) AS phone_service_count,
            SUM(MultipleLines_Flag) AS multiple_lines_count,
            SUM(OnlineSecurity_Flag) AS online_security_count,
            SUM(OnlineBackup_Flag) AS online_backup_count,
            SUM(DeviceProtection_Flag) AS device_protection_count,
            SUM(TechSupport_Flag) AS tech_support_count,
            SUM(StreamingTV_Flag) AS streaming_tv_count,
            SUM(StreamingMovies_Flag) AS streaming_movies_count
        FROM telecom_customers;
    """,
    
    'Service_Churn_Analysis': """
        SELECT 'OnlineSecurity' AS service, SUM(OnlineSecurity_Flag) AS users,
               SUM(CASE WHEN Churn_Flag=1 THEN 1 ELSE 0 END) AS churned,
               ROUND(SUM(CASE WHEN Churn_Flag=1 THEN 1 ELSE 0 END)/SUM(OnlineSecurity_Flag)*100,2) AS churn_rate_percentage
        FROM telecom_customers
        UNION ALL
        SELECT 'OnlineBackup', SUM(OnlineBackup_Flag), SUM(CASE WHEN Churn_Flag=1 THEN 1 ELSE 0 END),
               ROUND(SUM(CASE WHEN Churn_Flag=1 THEN 1 ELSE 0 END)/SUM(OnlineBackup_Flag)*100,2)
        FROM telecom_customers
        UNION ALL
        SELECT 'DeviceProtection', SUM(DeviceProtection_Flag), SUM(CASE WHEN Churn_Flag=1 THEN 1 ELSE 0 END),
               ROUND(SUM(CASE WHEN Churn_Flag=1 THEN 1 ELSE 0 END)/SUM(DeviceProtection_Flag)*100,2)
        FROM telecom_customers;
    """,
    
    'Revenue_Summary': """
        SELECT ROUND(SUM(TotalCharges),2) AS total_revenue,
               ROUND(AVG(TotalCharges),2) AS avg_revenue_per_customer
        FROM telecom_customers;
    """,
    
    'Revenue_by_Contract_Tenure': """
        SELECT Contract, tenure_group, COUNT(*) AS customer_count,
               ROUND(SUM(TotalCharges),2) AS total_revenue,
               ROUND(AVG(MonthlyCharges),2) AS avg_monthly_charge,
               RANK() OVER(PARTITION BY Contract ORDER BY SUM(TotalCharges) DESC) AS revenue_rank
        FROM telecom_customers
        GROUP BY Contract, tenure_group
        ORDER BY total_revenue DESC;
    """,
    
    'Payment_Method_Analysis': """
        SELECT PaymentMethod, COUNT(*) AS total_customers,
               SUM(Churn_Flag) AS churned_customers,
               ROUND(AVG(Churn_Flag)*100,2) AS churn_rate_percentage,
               ROUND(SUM(TotalCharges),2) AS total_revenue
        FROM telecom_customers
        GROUP BY PaymentMethod
        ORDER BY churn_rate_percentage DESC;
    """,
    
    'Paperless_Billing_Impact': """
        SELECT PaperlessBilling, COUNT(*) AS total_customers,
               SUM(Churn_Flag) AS churned_customers,
               ROUND(AVG(Churn_Flag)*100,2) AS churn_rate_percentage,
               ROUND(SUM(TotalCharges),2) AS total_revenue
        FROM telecom_customers
        GROUP BY PaperlessBilling;
    """,
    
    'Combined_Segment_Analysis': """
        WITH combined_segments AS (
            SELECT gender, SeniorCitizen, Partner, Dependents, Contract, tenure_group,
                   COUNT(*) AS total_customers,
                   SUM(Churn_Flag) AS churned_customers,
                   ROUND(AVG(Churn_Flag)*100,2) AS churn_rate_percentage,
                   ROUND(SUM(TotalCharges),2) AS total_revenue
            FROM telecom_customers
            GROUP BY gender, SeniorCitizen, Partner, Dependents, Contract, tenure_group
        )
        SELECT *
        FROM combined_segments
        ORDER BY churn_rate_percentage DESC, total_revenue DESC
        LIMIT 20;
    """
}

with pd.ExcelWriter('sql_output.xlsx', engine='openpyxl') as writer:
    for sheet_name, query in queries.items():
        df = pd.read_sql(query, conn)
        df.to_excel(writer, sheet_name=sheet_name, index=False)

# 4. Close connection
conn.close()

C:\Users\KIIT\AppData\Local\Temp\ipykernel_16520\1009440027.py:171: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)